# Generated by Django 4.0 on 2023-02-20 06:25

from django.db import migrations, models
import django.db.models.deletion
import instance.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_id', instance.models.ParameterIdField(editable=False, max_length=8, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('variable', models.CharField(max_length=100)),
                ('add_time', models.TimeField(auto_now_add=True)),
                ('update_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Time_frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_frame', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('strategy_id', instance.models.StrategyIdField(editable=False, max_length=8, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('script', models.CharField(max_length=100)),
                ('add_time', models.TimeField(auto_now_add=True)),
                ('update_time', models.TimeField(auto_now=True)),
                ('parameter', models.ManyToManyField(to='instance.Parameter')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('initialize_day', multiselectfield.db.fields.MultiSelectField(choices=[['0', 'Monday'], ['1', 'Tuesday'], ['2', 'Wednesday'], ['3', 'Thursday'], ['4', 'Friday']], max_length=100)),
                ('initialize_time', models.TimeField()),
                ('terminate_time', models.TimeField()),
                ('add_time', models.TimeField(auto_now_add=True)),
                ('update_time', models.TimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('parameters', models.JSONField(default=dict)),
                ('strategy_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.strategy')),
            ],
        ),
    ]
