# Generated by Django 4.0 on 2023-02-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='parameters',
        ),
    ]
